const GET_CATEGORIES = 'GET_CATEGORIES';
const GET_PRODUCTS = 'GET_PRODUCTS';
const ADD_TO_CART = 'ADD_TO_CART';
const GET_CARTITEMS = 'GET_CARTITEMS';

export {
    GET_CATEGORIES,
    GET_PRODUCTS,
    ADD_TO_CART,
    GET_CARTITEMS,
}